/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.cpp                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: prossi <prossi@student.42.fr>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/07/05 17:44:04 by prossi            #+#    #+#             */
/*   Updated: 2022/08/01 09:57:31 by prossi           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "ShrubberyCreationForm.hpp"
#include "RobotomyRequestForm.hpp"
#include "PresidentialPardonForm.hpp"
#include "Bureaucrat.hpp"

int main(void)
{
    try
	{
        ShrubberyCreationForm SCF("home");
       // Form *SCF = new ShrubberyCreationForm("home");
        Bureaucrat b1("Bob", 136);
        Bureaucrat b2("Jhon", 145);
        b2.signForm(SCF);
        b1.executeForm(SCF);

        b2.executeForm(SCF);
    }

	catch (std::exception & e) {
        std::cout << "Exception: " << e.what() << std::endl;
    }

    try
	{
        Form *SCF = new RobotomyRequestForm("home");
        Bureaucrat b1("Bob2", 44);
        Bureaucrat b2("Jhon2", 72);
        b2.signForm(*SCF);
        b1.executeForm(*SCF);

        b2.executeForm(*SCF);
        delete SCF;
    }

	catch (std::exception & e)
	{
        std::cout << "Exception: " << e.what() << std::endl;
    }

    try
	{
        Form *SCF = new PresidentialPardonForm("home");
        Bureaucrat b1("Bob2", 5);
        Bureaucrat b2("Jhon2", 24);
        b2.signForm(*SCF);
        b1.executeForm(*SCF);

        b2.executeForm(*SCF);
        delete SCF;
    }

	catch (std::exception & e)
	{
        std::cout << "Exception: " << e.what() << std::endl;
    }
}
